eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9101/eureka/,http://localhost:9102/eureka/

server:
  port: 9108

spring:
  application:
    name: service-feign

feign:
  hystrix:
    #开启熔断
    enable: true

