eureka:
  instance:
    # 服务续约任务的调用时间间隔，默认为90秒
    lease-expiration-duration-in-seconds: 10
    # 服务失效的时间，向服务端发送一次心跳，证明自己依然活着，默认30秒
    lease-renewal-interval-in-seconds: 5
  client:
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 5
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出，生产环境建议开启自我保护
    enable-self-preservation: false
    # 集群状态同步重试间隔
    registry-sync-retry-wait-ms: 5
    # 服务器节点的状态信息被更新的时间间隔，单位为毫秒，默认为30 * 1000
    peer-eureka-status-refresh-time-interval-ms: 5000
