eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9101/eureka/,http://localhost:9102/eureka/

server:
  port: 9103
